spring:
  datasource:
    url: jdbc:oracle:thin:@10.23.101.222:1521:hcc
    username: goss
    password: yiling
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  mapper-locations: com/example/mapper/*.xml

server:
  servlet:
    session:
      timeout: 1